version: '3.8'

services:
    web:
        env_file:
            - ../.env
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://kitchengpt_user:kitchengpt_password@db/kitchengpt_db

    db:
        image: postgres:13
        volumes:
            - ./postgres-init:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: kitchengpt_user
            POSTGRES_PASSWORD: kitchengpt_password
            POSTGRES_DB: kitchengpt_db

volumes:
    postgres_data:
